# backend/docker-compose.override.yml
services:
  db-restore:
    image: postgres:16
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGHOST: db
      PGUSER: mywebsite
      PGPASSWORD: password
      PGDATABASE: websitedb
    volumes:
      - ./seeds:/seeds:ro
    entrypoint: ["/bin/bash","-lc"]
    command: |
      set -e
      echo "Waiting for Postgres..."
      until pg_isready -h "$PGHOST" -U "$PGUSER" -d "$PGDATABASE" >/dev/null 2>&1; do sleep 1; done
      COUNT=$(psql -Atc "select count(*) from information_schema.tables where table_schema='public'")
      echo "Public tables count = $COUNT"
      if [ "$COUNT" -eq 0 ]; then
        echo "Restoring /seeds/websitedb.dump ..."
        pg_restore -v -U "$PGUSER" -d "$PGDATABASE" /seeds/websitedb.dump
        echo "Restore done."
      else
        echo "DB has tables. Skip restore."
      fi

  api:
    depends_on:
      db:
        condition: service_healthy
      db-restore:
        condition: service_completed_successfully
